include(../../libs/utils/utils.pri)
include(../../libs/utils3d/utils3d.pri)
include(../coreplugin/coreplugin.pri)
include(../editorplugin/editorplugin.pri)
include(../gldatabaseplugin/gldatabaseplugin.pri)
